[linux_servers]
zabbix_server ansible_host=35.154.219.63 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/zabbix-ansible/my-key.pem
demo-server-1 ansible_host=65.0.80.223 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ubuntu/zabbix-ansible/my-key.pem
