- name: Create host in Zabbix
  community.zabbix.zabbix_host:
    host_name: "{{ inventory_hostname }}"
    visible_name: "{{ inventory_hostname }}"
    host_groups:
      - "{{ zabbix_host_group }}"
    link_templates:
      - "{{ zabbix_template }}"
    interfaces:
      - type: agent
        main: 1
        useip: 1
        ip: "{{ ansible_host }}"
        port: "10050"
    state: present
